# -*- coding: utf-8 -*-
"""NLP1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_Yh-HEWFW4_jln3gZfogdQuZc8PMHWA
"""

import re

resumes = [
"""
Name: Rahul Sharma
Email: rahul@gmail.com
Mobile: 9876543210
Skills: Python, Java, SQL, Machine Learning
Experience: 3 years
""",

"""
Name: Priya Singh
Email: priya123@yahoo.com
Mobile: 9123456780
Skills: Java, SQL
Experience: 1 years
""",

"""
Name: Karthik R
Email: karthik@gmail.com
Mobile: 9988776655
Skills: Python, NLP, SQL
Experience: 5 years
"""
]

skill_list = ["Python", "Java", "SQL", "Machine Learning", "NLP"]

eligible = []

for resume in resumes:

    name = re.search(r"Name\s*:\s*(.*)", resume)
    name = name.group(1)

    email = re.search(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", resume)
    email = email.group()

    mobile = re.search(r"\d{10}", resume)
    mobile = mobile.group()

    exp = re.search(r"(\d+)\s+years", resume)
    experience = int(exp.group(1))

    skills = []

    for skill in skill_list:
        if re.search(skill, resume, re.IGNORECASE):
            skills.append(skill)

    print("\nCandidate Profile")
    print("Name:", name)
    print("Email:", email)
    print("Mobile:", mobile)
    print("Skills:", ", ".join(skills))
    print("Experience:", experience, "Years")

    if experience >= 2 and "Python" in skills:
        eligible.append(name)

print("\nEligible Candidates")

for candidate in eligible:
    print(candidate)

import re

products = [
    "Laptop",
    "Laptop Bag",
    "Laptop Stand",
    "Mouse",
    "Wireless Mouse",
    "Keyboard",
    "Gaming Keyboard",
    "Monitor",
    "Smart Phone",
    "Phone Case",
    "Bluetooth Speaker",
    "Smart Watch",
    "USB Cable",
    "Power Bank",
    "Headphones"
]

keyword = input("Enter search keyword: ")

exact = []
prefix = []
suffix = []
partial = []
case_insensitive = []

for product in products:
    if re.fullmatch(keyword, product):
        exact.append(product)

    if re.match(keyword, product):
        prefix.append(product)

    if re.search(keyword + r"$", product):
        suffix.append(product)

    if re.search(keyword, product):
        partial.append(product)

    if re.search(keyword, product, re.IGNORECASE):
        case_insensitive.append(product)

print("\nExact Search")
for i in exact:
    print(i)

print("\nPrefix Search")
for i in prefix:
    print(i)

print("\nSuffix Search")
for i in suffix:
    print(i)

print("\nPartial Search")
for i in partial:
    print(i)

print("\nCase-Insensitive Search")
for i in case_insensitive:
    print(i)

print("\nSearch Report")
print("Exact Matches :", len(exact))
print("Prefix Matches :", len(prefix))
print("Suffix Matches :", len(suffix))
print("Partial Matches :", len(partial))
print("Case-Insensitive Matches :", len(case_insensitive))

import re

reg_no = input("Enter Register Number: ")
email = input("Enter Institutional Email: ")
course = input("Enter Course Code: ")
semester = input("Enter Semester: ")
mobile = input("Enter Mobile Number: ")

reg_valid = re.fullmatch(r"\d{2}[A-Z]{3}\d{4}", reg_no)
email_valid = re.fullmatch(r"[a-zA-Z0-9._%+-]+@saveetha\.com", email)
course_valid = re.fullmatch(r"[A-Z]{2,4}\d{3}", course)
semester_valid = re.fullmatch(r"[1-8]", semester)
mobile_valid = re.fullmatch(r"[6-9]\d{9}", mobile)

if reg_valid:
    print("Register Number: Valid")
else:
    print("Register Number: Invalid")

if email_valid:
    print("Institutional Email: Valid")
else:
    print("Institutional Email: Invalid")

if course_valid:
    print("Course Code: Valid")
else:
    print("Course Code: Invalid")

if semester_valid:
    print("Semester: Valid")
else:
    print("Semester: Invalid")

if mobile_valid:
    print("Mobile Number: Valid")
else:
    print("Mobile Number: Invalid")

if reg_valid and email_valid and course_valid and semester_valid and mobile_valid:
    print("\nRegistration Status: Registration Successful")
else:
    print("\nRegistration Status: Registration Failed")