# -*- coding: utf-8 -*-
"""NLP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DT_KF5AilbFT1xGhQELDTFfTb4pWFQ06
"""

import re

email = input("Enter Email: ")
phone = input("Enter Phone Number: ")
password = input("Enter Password: ")
pin = input("Enter PIN Code: ")
text = input("Enter a sentence: ")

print("\n----- RESULTS -----")

email_pattern = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
if re.match(email_pattern, email):
    print("Email: Valid")
else:
    print("Email: Invalid")

phone_pattern = r'^[6-9]\d{9}$'
if re.match(phone_pattern, phone):
    print("Phone Number: Valid")
else:
    print("Phone Number: Invalid")

password_pattern = r'^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&]).{8,}$'
if re.match(password_pattern, password):
    print("Password: Strong")
else:
    print("Password: Weak")

pin_pattern = r'^\d{6}$'
if re.match(pin_pattern, pin):
    print("PIN Code: Valid")
else:
    print("PIN Code: Invalid")

urls = re.findall(r'https?://\S+', text)
print("URLs:", urls)

dates = re.findall(r'\d{2}/\d{2}/\d{4}', text)
print("Dates:", dates)

hashtags = re.findall(r'#\w+', text)
print("Hashtags:", hashtags)

currency = re.findall(r'₹\d+', text)
print("Currency:", currency)

numbers = re.findall(r'\d+', text)
print("Numbers:", numbers)

words = re.findall(r'\b[A-Z][a-zA-Z]*\b', text)
print("Capital Words:", words)